# This spec is meant to be consumed only from a root image which ends up being used as uefi image.
# TODO: verify checksum

prelude:
- zypper in -y xz wget tar
- wget https://github.com/ivandavidov/systemd-boot/releases/download/systemd-boot_26-May-2018/systemd-boot_26-May-2018.tar.xz
- mkdir -p /systemd-boot
- tar -xvf systemd-boot_26-May-2018.tar.xz -C /systemd-boot
steps:
- mkdir -p /EFI/BOOT
- cp /systemd-boot/systemd-boot*/uefi_root/EFI/BOOT/BOOTx64.EFI /EFI/BOOT
- cp /systemd-boot/systemd-boot*/uefi_root/EFI/BOOT/BOOTIA32.EFI /EFI/BOOT

requires:
- name: "base"
  category: "distro"
  version: ">=0"
