requires:
- name: "golang"
  category: "build"
  version: ">=0"
env:
- PATH=$PATH:/usr/local/go/bin
- GOPATH=/luetbuild/go
- GO111MODULE=on
- CGO_ENABLED=0
- LDFLAGS="-s -w"
prelude:
{{ if .Values.distribution }}
{{if eq .Values.distribution "opensuse" }}
- zypper in -y git upx
{{else if eq .Values.distribution "fedora" }}
- dnf install -y git upx
{{else if eq .Values.distribution "ubuntu" }}
- apt-get install -y git upx
{{end}}
{{end}}
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   mkdir -p /luetbuild/go/src/github.com/mudler && cd /luetbuild/go/src/github.com/mudler && \
   git clone https://github.com/mudler/yip && cd yip && git checkout "${PACKAGE_VERSION}" -b build
steps:
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   cd /luetbuild/go/src/github.com/mudler/yip && make build-small && mv yip /usr/bin/yip
includes:
- /usr/bin/yip
