name: "Default deployment"
stages:
  rootfs.after:
    - if: '[ -f "/run/cos/recovery_mode" ]'
      name: "Repart image"
      layout:
        device:
          label: COS_RECOVERY
        add_partitions:
          - fsLabel: COS_STATE
            size: 9192
            pLabel: state
            filesystem: ext4
          - fsLabel: COS_PERSISTENT
            pLabel: persistent
            filesystem: ext4
