# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "cos"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4098", "--cpus", "2"]
  end

  config.vm.provider :libvirt do |libvirt|
    config.vm.guest = :linux
    config.vm.synced_folder ".", "/vagrant", disabled: true
    libvirt.driver = "kvm"
    libvirt.memory = 4096
    libvirt.cpus = 2
    config.vm.network "forwarded_port", guest: 22, host: 2222
  end
    
end
