# The boot assessment works in this way:
# - After we upgrade, we set a grub env sentinel variable indicating that we did run an upgrade
# - At the first boot, if we did an upgrade, we set another sentinel variable, which indicates we are trying to boot
# - If we boot fine, we remove both sentinels
# - If we get back again at the GRUB menu, a failure must have occurred and we select the fallback entry, creating also
#   sentinels files and a specific cmdline option indicating we failed booting after an upgrade

name: "Boot assessment"
stages:
    boot.before:
    # Remove any grub sentinel and add
    # System sentinel to /run to indicate if we are booting after a failed upgrade.
    # This needs to run only on the active partition.
    # To note, we could similarly enable boot assessment always, also besides upgrades.
    # In this case it is enough to reset only boot_assessment_tentative here, and set 
    # enable_boot_assessment to 'yes'.
    # This can be then customized easily by having a cloud-config file which always enables boot assessment on 
    # the boot stage.
    - name: "Remove GRUB sentinels"
      if: '[ -f "/run/elemental/active_mode" ]'
      commands:
      - |
          mount -o rw,remount /run/elemental/efi
          grub2-editenv /run/elemental/efi/boot_assessment set enable_boot_assessment=
          grub2-editenv /run/elemental/efi/boot_assessment set boot_assessment_tentative=
          mount -o ro,remount /run/elemental/efi
    - name: "Create upgrade failure sentinel if necessary"
      if: cat /proc/cmdline | grep -q "upgrade_failure"
      files:
      - path: /run/elemental/upgrade_failure
        content: "1"
        permissions: 0600
        owner: 0
        group: 0
    after-install:
    # After install, reset, and upgrade, we install additional GRUB configuration for boot assessment into COS_GRUB.

    # Here we hook the boot assessment configuration to 'grubcustom'
    # we do that selectively in order to just "append" eventual other configuration provided.
    # XXX: maybe we should just write to /grubcustom and override any other custom grub?
    - &customhook
      name: "Hook boot assessment grub configuration"
      if: '[ ! -f "/run/elemental/efi/grubcustom" ]'
      files:
      - path: "/run/elemental/efi/grubcustom"
        permissions: 0600
        content: |
          set bootfile="/grub_boot_assessment"
          search --no-floppy --file --set=bootfile_loc "${bootfile}"
          if [ "${bootfile_loc}" ]; then
            source "(${bootfile_loc})${bootfile}"
          fi

    # Overrides the active cmdline by adding "rd.emergency=reboot", "rd.shell=0" and "panic=5"
    # so that any failure in booting initramfs or kernel loading results in a reboot.
    # It loads then the boot assessment environment and overrides default boot target if
    # a boot failure is detected.
    # A boot is considered failed when both sentinel are present ( upgrade triggered, tentative ).
    # The tentative sentinel is set after an upgrade was triggered.
    # This configuration is separated so it can be tracked separately from the install hook
    # 
    - &bootgrub
      name: "Add boot assessment grub configuration"
      if: '[ ! -f "/run/elemental/efi/grub_boot_assessment" ]'
      files:
       - path: "/run/elemental/efi/grub_boot_assessment"
         owner: 0
         group: 0
         permissions: 0600
         content: |
            set extra_active_cmdline="rd.emergency=reboot rd.shell=0 panic=5 systemd.crash_reboot systemd.crash_shell=0"
            set boot_assessment_file="/boot_assessment"
            if [ -f "${boot_assessment_file}" ]; then
              load_env -f "${boot_assessment_file}"
            fi
            if [ "${enable_boot_assessment}" = "yes" -o "${enable_boot_assessment_always}" = "yes" ]; then
              if [ -z "${selected_entry}" ]; then
                if [ "${boot_assessment_tentative}" = "yes" ]; then
                  set default="1"
                  set extra_passive_cmdline="upgrade_failure"
                else
                  set boot_assessment_tentative="yes"
                  save_env -f "${boot_assessment_file}" boot_assessment_tentative
                fi
              fi
            fi

    # Here we do enable boot assessment for the next bootup.
    # Similarly, we could trigger boot assessment in other cases
    after-upgrade:
    - name: "Set upgrade sentinel on active"
      if: '[ ! -f "/run/elemental/recovery_mode" ]' 
      commands:
      - grub2-editenv /run/elemental/efi/boot_assessment set enable_boot_assessment=yes
    - name: "Set upgrade sentinel on recovery"
      if: '[ -f "/run/elemental/recovery_mode" ]' 
      commands:
      - grub2-editenv /run/elemental/efi/boot_assessment set enable_boot_assessment=yes
    # We do re-install hooks here if needed to track upgrades of boot assessment
    - <<: *customhook
    - <<: *bootgrub

    after-reset:
    - name: "Remove GRUB sentinels"
      commands:
      - |
          grub2-editenv /run/elemental/efi/boot_assessment set enable_boot_assessment=
          grub2-editenv /run/elemental/efi/boot_assessment set boot_assessment_tentative=
    # Reset completely restores COS_STATE, so we re-inject ourselves
    - <<: *customhook
    - <<: *bootgrub
