requires:
  - name: "golang{{- if .Values.fips -}}-fips{{- end -}}"
    category: "build"
    version: ">=0"
env:
{{ template "golang_env" }}
{{if .Values.fips}}
- CGO_ENABLED=1
{{ else }}
- CGO_ENABLED=0
- LDFLAGS="-s -w"
{{ end }}

prelude:
  {{ template "golang_deps" .}}
  {{ $opts:= dict "version" ( index .Values.labels "git.hash" ) "org" ( index .Values.labels "github.owner" ) "repo" ( index .Values.labels "github.repo" ) }}
  {{ template "golang_download_package" $opts}}
steps:
  - |
    PACKAGE_VERSION=${PACKAGE_VERSION%\-*} && \
    cd /luetbuild/go/src/github.com/{{ ( index .Values.labels "github.owner" ) }}/{{ ( index .Values.labels "github.repo" ) }} && \
    make build && \
    mv bin/{{.Values.bin_name}} /usr/bin/{{.Values.bin_name}}
{{ if .Values.fips }}
  # Check that we build with fips
  - go tool nm /usr/bin/{{.Values.name}} | grep '_Cfunc__goboringcrypto_' 1> /dev/null
{{ end }}

includes:
  - /usr/bin/{{.Values.bin_name}}