requires:
- name: "base"
  category: "distro"
  version: ">=0"
# cos-setup is required in module-setup and embedded in the initramfs
- name: "cos-setup"
  category: "system"
  version: ">=0"

copy:
# yip is required in module-setup and embedded in the initramfs. 
# We don't put it in requires to avoid pulling golang sublayers
- package: 
    category: "toolchain"
    name: "yip"
    version: ">=0"
  source: "/usr/bin/yip"
  destination: "/usr/bin/yip"

steps:
{{ if .Values.distribution }}
{{if eq .Values.distribution "opensuse" }}
# Mount /tmp as tmpfs by default as set by systemd itself
- cp /usr/share/systemd/tmp.mount /etc/systemd/system
{{end}}
{{end}}
- cp -r 30cos-immutable-rootfs /usr/lib/dracut/modules.d
- |
    kernel=$(ls /lib/modules | head -n1) && \
    dracut --verbose --no-hostonly --omit multipath --no-hostonly-cmdline --xz \
        -f "/boot/initrd-${kernel}" --add " dmsquash-live cos-immutable-rootfs " \
        "${kernel}" && \
    ln -sf "initrd-${kernel}" /boot/initrd
