requires:
- name: "base"
  category: "distro"
  version: ">=0"

steps:
- |
    kernel=$(ls /lib/modules | head -n1) && \
    dracut --verbose --no-hostonly --no-hostonly-cmdline --xz \
        -f "/boot/initrd-${kernel}" --add " dmsquash-live " \
        --include "/luetbuild/cos-config-launcher.sh" \
        "/lib/dracut/hooks/pre-pivot/30cos-config.sh" "${kernel}" && \
    ln -sf "initrd-${kernel}" /boot/initrd
