requires:
- name: "base-dracut-modules"
  category: "system"
  version: ">=0"
- name: "kernel"
  category: "system"
  version: ">=0"
- name: "immutable-rootfs"
  category: "system"
  version: ">=0"

steps:
# Create initrd
- |
    kernel=$(ls /lib/modules | head -n1) && \
    dracut -f "/boot/initrd-${kernel}" "${kernel}" && \
    ln -sf "initrd-${kernel}" /boot/initrd