# Refer to https://luet-lab.github.io/docs/docs/concepts/packages/specfile/#build-specs
# for the syntax format
requires:
- name: "cos-setup"
  category: "system"
  version: ">=0"
- name: "installer"
  category: "utils"
  version: ">=0"
- name: "cloud-config"
  category: "system"
  version: ">=0"
- name: "immutable-rootfs"
  category: "system"
  version: ">=0"
- name: "cos-features"
  category: "system"
  version: ">=0"
- name: "grub-config"
  category: "system"
  version: ">=0"

# Skip selinux policies for recovery
{{if ne .Values.category "recovery" }}

- name: "selinux-policies"
  category: "system"
  version: ">=0"

{{end}}


# https://luet-lab.github.io/docs/docs/concepts/packages/specfile/#copy
copy:
- package: 
    category: "toolchain"
    name: "yip"
    version: ">=0"
  source: "/usr/bin/yip"
  destination: "/usr/bin/yip"
- package: 
    category: "toolchain"
    name: "luet"
    version: ">=0"
  source: "/usr/bin/luet"
  destination: "/usr/bin/luet"
- package:
    category: "toolchain"
    name: "luet-mtree"
    version: ">=0"
  source: "/usr/bin/luet-mtree"
  destination: "/usr/bin/luet-mtree"
- package:
    category: "toolchain"
    name: "yq"
    version: ">=0"
  source: "/usr/bin/yq"
  destination: "/usr/bin/yq"

# Templated package https://luet-lab.github.io/docs/docs/concepts/packages/templates/
steps:
- sed -i 's/:BRANDING:/{{.Values.brand_name}}/g' setup.yaml
- sed -i 's/:VERSION:/{{.Values.version}}/g' setup.yaml
- sed -i 's/:PRETTY_NAME:/{{.Values.brand_name}} v{{.Values.version}}/g' setup.yaml
- yip setup.yaml

# See https://luet-lab.github.io/docs/docs/concepts/packages/specfile/#package-by-container-content
unpack: true

# Files to exclude from the final 
# artifact 
# See also: https://luet-lab.github.io/docs/docs/concepts/packages/specfile/#excludingincluding-files-explictly
excludes:
- ^/var/cache/luet
- ^/luetbuild
- ^/srv/.*
- ^/root/.bash_history
- ^/run/reboot-needed

# Zypper
- ^/var/lib/zypp
- ^/var/cache/zypp
- ^/usr/share/zypper
- ^/usr/share/zypp
- ^/usr/share/zsh
- ^/usr/share/licenses/zypper
- ^/usr/bin/zypp-.*
- ^/usr/bin/zypper
- ^/usr/lib/zypp$
- ^/usr/lib/zypper
- ^/usr/lib/rpm
- ^/usr/bin/yzpper
- ^/usr/sbin/zypp-.*
- ^/usr/bin/zypp-.*
- ^/usr/bin/susetags2solv
- ^/run/zypp.*
- ^/etc/zypp
- ^/usr/bin/rpm.*
- ^/var/lib/rpm
- ^/usr/lib64/rpm-plugins 
# Yast
- ^/var/lib/YaST2

#- ^/usr/local
- ^/usr/local/bin
- ^/usr/local/go
- ^/usr/local/include
- ^/usr/local/lib.*
- ^/usr/local/man
- ^/usr/local/sbin
- ^/usr/local/share
- ^/usr/local/src
- ^/usr/local/games
