#
# cOS-toolkit Makefile.docs
#
#

export BASE_URL?=https://rancher.github.io/elemental-toolkit/

docs-deps: $(LUET) $(HUGO) $(YQ)

docs-serve: docs-deps
	hugo -s "$(ROOT_DIR)/docs" serve 

docs-generate:
	scripts/docs-generate-packages.sh $(ROOT_DIR)/packages

docs-build: docs-deps docs-generate
	scripts/docs-build.sh