.PHONY: prepare-test
prepare-test:
ifeq ("$(QCOW2)","")
	@echo "No qcow2 disk found, run 'make build-disk' first"
	@exit 1
endif
	@scripts/run_vm.sh start $(QCOW2)
	@echo "VM started from $(QCOW2)"

.PHONY: prepare-installer-test
prepare-installer-test:
ifeq ("$(ISO)","")
	@echo "No ISO image found, run 'make build-iso' first"
	@exit 1
endif
	@scripts/run_vm.sh start $(ISO)
	@echo "VM started from $(ISO)"

.PHONY: test-clean
test-clean:
	@scripts/run_vm.sh stop
	@scripts/run_vm.sh clean

.PHONY: test-iso
test-iso: test-installer

# TODO review and clean installer test code, many tests are disabled
.PHONY: test-installer
test-installer: prepare-installer-test
	cd tests && go run github.com/onsi/ginkgo/v2/ginkgo $(GINKGO_ARGS) ./installer

.PHONY: test-smoke
test-smoke: prepare-test
	cd tests && go run github.com/onsi/ginkgo/v2/ginkgo $(GINKGO_ARGS) ./smoke

.PHONY: test-hooks
test-hooks: prepare-test
	cd $(ROOT_DIR)/tests && go run github.com/onsi/ginkgo/v2/ginkgo $(GINKGO_ARGS) ./hooks

.PHONY: test-recovery
test-recovery: prepare-test
	cd $(ROOT_DIR)/tests && go run github.com/onsi/ginkgo/v2/ginkgo $(GINKGO_ARGS) ./recovery

.PHONY: test-fallback
test-fallback: prepare-test
	cd $(ROOT_DIR)/tests && go run github.com/onsi/ginkgo/v2/ginkgo $(GINKGO_ARGS) ./fallback

.PHONY: test-reset
test-reset: prepare-test
	cd $(ROOT_DIR)/tests && go run github.com/onsi/ginkgo/v2/ginkgo $(GINKGO_ARGS) ./reset

.PHONY: test-upgrades-local
test-upgrades-local: prepare-test
	cd $(ROOT_DIR)/tests && go run github.com/onsi/ginkgo/v2/ginkgo $(GINKGO_ARGS) ./upgrades-local

# TODO missing signed and unsigned images to upgrade to
#test-upgrades-images-signed: prepare-test
#	cd $(ROOT_DIR)/tests && go run github.com/onsi/ginkgo/v2/ginkgo $(GINKGO_ARGS) ./upgrades-images-signed
