#
# cOS-toolkit Makefile.test
#
#

GINKGO_ARGS?=-progress -v --failFast -flakeAttempts 2 -r

GINKGO?=$(shell which ginkgo 2> /dev/null)
ifeq ("$(GINKGO)","")
GINKGO="/usr/bin/ginkgo"
endif

VAGRANT?=$(shell which vagrant 2> /dev/null)
ifeq ("$(VAGRANT)","")
VAGRANT="/usr/bin/vagrant"
endif

#
# Find correct (hashicorp/packer) binary
#

# if PACKER is pre-set, leave it alone
ifeq ("$(PACKER)","")
PACKER=$(shell which packer 2> /dev/null)
ifeq ("$(PACKER)","")
PACKER="/usr/bin/packer"
endif
endif

$(PACKER):
ifneq ($(shell id -u), 0)
	@echo "'$@' is missing and you must be root to install it."
	@exit 1
else
	$(LUET) install -y utils/packer
endif

#
# VirtualBox
#

VBOXMANAGE?=$(shell which VBoxManage 2> /dev/null)
ifeq ("$(VBOXMANAGE)","")
VBOXMANAGE="/usr/bin/VBoxManage"
endif

#
# VBoxManage is used to run a headless VirtualBox instance
#
$(VBOXMANAGE):
ifneq ($(shell id -u), 0)
	@echo "'$@' is missing and you must be root to install it."
	@exit 1
else
	@echo "Please install VirtualBox."
	@exit 1
endif

BOXFILE=$(shell ls $(ROOT_DIR)/packer/*.box 2> /dev/null)
ifeq ("$(BOXFILE)","")
BOXFILE="$(ROOT_DIR)/packer/cOS.box"
endif

.PHONY: packer
#
# target 'packer' creates a compressed tarball with an 'ova' file
#
packer: $(BOXFILE)

packer-clean:
	rm -rf $(BOXFILE)

$(BOXFILE): $(PACKER)
ifeq ("$(PACKER)","/usr/sbin/packer")
	@echo "The 'packer' binary at $(PACKER) might be from cracklib"
	@echo "Please set PACKER to the correct binary before calling make"
	@exit 1
endif
ifeq ("$(ISO)","")
	@echo "Please run 'make iso' or 'make local-iso' first"
	@exit 1
endif
	cd $(ROOT_DIR)/packer && $(PACKER) build -var "iso=$(ISO)" $(PACKER_ARGS) images.json

#
# ------------ actual test targets ------------
#

test: test-clean vagrantfile prepare-test test-smoke test-upgrades-signed test-upgrades-unsigned test-features test-fallback test-recovery

#
# remove test artifacts
#

clean_test: test-clean packer-clean


prepare-test: $(VAGRANT) $(BOXFILE)
	vagrant box add cos $(BOXFILE)
	cd $(ROOT_DIR)/tests && vagrant up || true

vagrantfile: $(ROOT_DIR)/tests/Vagrantfile $(VAGRANT)

$(ROOT_DIR)/tests/Vagrantfile: $(VAGRANT)
	cd $(ROOT_DIR)/tests && vagrant init cos

test-clean:
	(cd $(ROOT_DIR)/tests && vagrant destroy) 2> /dev/null || true
	(vagrant box remove cos) 2> /dev/null || true

$(VAGRANT):
	@echo "'vagrant' not found."
	@exit 1

test-fallback: $(GINKGO)
	cd $(ROOT_DIR)/tests && $(GINKGO) $(GINKGO_ARGS) ./fallback

test-features: $(GINKGO)
	cd $(ROOT_DIR)/tests && $(GINKGO) $(GINKGO_ARGS) ./features

test-upgrades-images-signed: $(GINKGO)
	cd $(ROOT_DIR)/tests && $(GINKGO) $(GINKGO_ARGS) ./upgrades-images-signed

test-upgrades-images-unsigned: $(GINKGO)
	cd $(ROOT_DIR)/tests && $(GINKGO) $(GINKGO_ARGS) ./upgrades-images-unsigned

test-smoke: $(GINKGO)
	cd $(ROOT_DIR)/tests && $(GINKGO) $(GINKGO_ARGS) ./smoke

test-recovery: $(GINKGO)
	cd $(ROOT_DIR)/tests && $(GINKGO) $(GINKGO_ARGS) ./recovery

$(GINKGO):
	@echo "'ginkgo' not found."
	@exit 1
