stages:
   network:
     - name: "Setup users"
       ensure_entities:
       - path: /etc/passwd
         entity: |
            kind: "user"
            username: "vagrant"
            password: "x"
            homedir: "/run/tmp/vagrant"
            shell: "/bin/bash"
       - path: /etc/shadow
         entity: |
            kind: "shadow"
            username: "vagrant"
            password: ""
       commands:
       - mkdir -p /run/tmp/vagrant
     - name: "Setup pubkey"
       authorized_keys:
        vagrant:
        - https://raw.githubusercontent.com/hashicorp/vagrant/main/keys/vagrant.pub
name: "Setup for the vagrant user"
