requires:
- name: "cos-config-tmpl" 
  category: "utils"
  version: ">=0"
- name: "cos-config" 
  category: "system"
  version: ">=0"

steps:
- mkdir -p {{.Values.oem_dir}}
- chmod 700 {{.Values.oem_dir}}
- cp -rfv oem/{{.Values.oem_file}} {{.Values.oem_dir}}
- chmod 600 {{.Values.oem_dir}}/{{.Values.oem_file}}
{{ if .Values.templated }}
- cos-tmpl-render {{.Values.oem_dir}}/{{.Values.oem_file}}
{{ end }}

{{ if eq .Values.oem_file "02_upgrades.yaml" }}
{{ if .Values.codename }}
- sed -i 's/:FLAVOR:/{{.Values.codename}}/g' {{.Values.oem_dir}}/02_upgrades.yaml
{{end}}
{{ if .Values.arch }}
  {{if eq .Values.arch "x86_64"}}
- sed -i 's/:ARCH://g' {{.Values.oem_dir}}/02_upgrades.yaml
  {{end}}
  {{if eq .Values.arch "aarch64"}}
- sed -i 's/:ARCH:/-arm64/g' {{.Values.oem_dir}}/02_upgrades.yaml
  {{end}}
{{end}}
{{ end }}
