requires:
- name: "base"
  category: "distro"
  version: ">=0"

prelude:
{{ template "distro_install" (dict "Values" .Values "Packages" "curl")}}
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\-*} && \
   curl -LO https://kernel.org/pub/linux/utils/boot/syslinux/syslinux-$PACKAGE_VERSION.tar.xz && \
   echo "{{ ( index .Values.labels "package.checksum" ) }}  syslinux-$PACKAGE_VERSION.tar.xz" | sha256sum -c && \
   mkdir -p /syslinux && \
   tar -xvf syslinux-$PACKAGE_VERSION.tar.xz -C /syslinux
steps:
- |
   mkdir -p /output/boot/syslinux && \
   PACKAGE_VERSION=${PACKAGE_VERSION%\-*} && \
   mv /syslinux/syslinux-$PACKAGE_VERSION/bios/core/isolinux.bin /output/boot/syslinux && \
   mv /syslinux/syslinux-$PACKAGE_VERSION/bios/com32/elflink/ldlinux/ldlinux.c32 /output/boot/syslinux && \
   mv /syslinux/syslinux-$PACKAGE_VERSION/bios/mbr/isohdpfx.bin /output/boot/syslinux
package_dir: /output
