name: Build CLI
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: go.mod
      - name: Build
        run: make build-cli
      - name: Analysis
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9
        with:
          args: -v
      - name: Run tests
        run: |
          make test-cli
          sudo env PATH="$PATH" make test-root
      - name: Merge coverage
        run: |
          echo "mode: atomic" > coverage.out
          grep -v "mode: atomic" coverage.txt >> coverage.out
          grep -v "mode: atomic" coverage_root.txt >> coverage.out
