name: nightly

on:
  workflow_dispatch:
  schedule:
    # run at 02:30 UTC every night
    - cron:  '30 2 * * *'

jobs:
  build-toolkit:
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    env:
      PLATFORM: x86_64
      TOOLKIT_REPO: ghcr.io/${{github.repository}}/elemental-cli 
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: |
          git fetch --prune --unshallow
      - name: Log in to ghcr.io
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build toolkit
        run: |
          make DOCKER_ARGS=--push VERSION=nightly build
